apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-namespace: devtroncd
  name: Test-Service
  description: |
    Test Backstage
spec:
  type: service
  owner: pjhy10221
  lifecycle: test
